### ISSUE TITLE
BlackBerry10 UI Changes

### ISSUE THREAD

**Issue by stmblfrcr** [gpodder/gpodder-bb10#9]
thanks for supporting BlackBerry. I‘m sorry, but I find the latest UI changes to be rather strange. The toolbar is purple now and on top (as intended I guess), which doesn‘t really fit OS guidelines. I actually liked the „old" grey design better (also with the vellipsis instead of the stack icon). At least it looked similar to BlackBerry Cascades. Now it appears to look more like Android. But I guess a reworked, „Built for BlackBerry“ UI just like Sailfish is out of the question? Thanks for making the store build free by the way!

**Comment by thp** [comment]
The problem was that maintaining two UIs in the QML codebase was difficult, and lead to double the testing requirement (and when new stuff was added, double the implementation requirement).

Right now, it's mostly what the gPodder 4 Android UI looks like (gPodder's Android and BB10 ports share the same UI at the moment). That doesn't mean we follow the Android UI guidelines, it just happens to look Android-ish.

A native Cascades UI is mostly out of the question at the moment, as Cascades is still built on Qt 4, and gPodder uses Qt 5. Even if Cascades were to be ported to Qt 5 or Qt Quick Controls would support a Cascades style, there would still need to be someone who actually writes and maintains this stuff (and it probably won't work anymore on the Blackberry Playbook, which currently still works with the pure QML UI we are using right now). I don't really have time for this (that's one of the reason why I'm trying to keep one QML UI for mobile platforms, with Sailfish being the exception at the moment; one exception that might come in the future is a QML UI for Desktop using Qt Quick Controls).

Feel free to step up as the gPodder 4 Blackberry UI maintainer, though - if you want to invest some time in this, having a native UI would obviously be something that would be useful to BB10 users (we can still build the "pure QML" variant of the UI for Playbook users).
